ALTER TABLE users ADD COLUMN nickname TEXT;
ALTER TABLE users ADD COLUMN department TEXT;
ALTER TABLE users ADD COLUMN gpa REAL DEFAULT 0.0;
ALTER TABLE courses ADD COLUMN department TEXT;
ALTER TABLE courses ADD COLUMN prerequisites TEXT DEFAULT 'None';
ALTER TABLE courses ADD COLUMN credits INTEGER DEFAULT 3;
ALTER TABLE student_courses ADD COLUMN grade TEXT DEFAULT 'N/A';
CREATE TABLE IF NOT EXISTS notifications (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message     TEXT    NOT NULL,
    is_read     INTEGER DEFAULT 0,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
